import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { bsScore, type BSDomain } from "../src/core";

type Item = { title?: string; body?: string; diff?: string; label: "slop" | "clean" };
type Counts = { tp: number; tn: number; fp: number; fn: number };

const domains: BSDomain[] = ["code-review", "content-seo", "social-news"];

async function loadItems(domain: BSDomain, label: "slop" | "clean") {
  const dir = join(process.cwd(), "data", "bake-off", domain, label);
  const files = await readdir(dir).catch(() => []);
  const items: Item[] = [];
  for (const file of files.filter((name) => name.endsWith(".json"))) {
    items.push(JSON.parse(await readFile(join(dir, file), "utf8")) as Item);
  }
  return items;
}

function metrics({ tp, tn, fp, fn }: Counts) {
  const total = tp + tn + fp + fn || 1;
  const precision = tp / (tp + fp || 1);
  const recall = tp / (tp + fn || 1);
  const f1 = (2 * precision * recall) / (precision + recall || 1);
  return { accuracy: (tp + tn) / total, precision, recall, f1 };
}

async function main() {
  const lines = ["# BS Meter Bake-Off", "", "Generated by `scripts/run-bakeoff.ts`.", ""];
  for (const domain of domains) {
    const items = [...(await loadItems(domain, "slop")), ...(await loadItems(domain, "clean"))];
    const counts: Counts = { tp: 0, tn: 0, fp: 0, fn: 0 };
    for (const item of items) {
      const text = item.body ?? "";
      const result = bsScore(text, { domain, context: { title: item.title, diff: item.diff } });
      const predictedSlop = result.score > 50;
      if (item.label === "slop" && predictedSlop) counts.tp += 1;
      if (item.label === "slop" && !predictedSlop) counts.fn += 1;
      if (item.label === "clean" && predictedSlop) counts.fp += 1;
      if (item.label === "clean" && !predictedSlop) counts.tn += 1;
    }
    const m = metrics(counts);
    lines.push(`## ${domain}`, "", `Samples: ${items.length}`, "", "| Metric | Value |", "| --- | ---: |",
      `| Accuracy | ${m.accuracy.toFixed(3)} |`, `| Precision | ${m.precision.toFixed(3)} |`,
      `| Recall | ${m.recall.toFixed(3)} |`, `| F1 | ${m.f1.toFixed(3)} |`, "",
      "| Confusion Matrix | Predicted Slop | Predicted Clean |", "| --- | ---: | ---: |",
      `| Actual Slop | ${counts.tp} | ${counts.fn} |`, `| Actual Clean | ${counts.fp} | ${counts.tn} |`, "");
  }
  await writeFile(join(process.cwd(), "docs", "BAKE_OFF.md"), lines.join("\n"));
  console.log("Wrote docs/BAKE_OFF.md");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
